load("@hedron_compile_commands//:refresh_compile_commands.bzl", "refresh_compile_commands")

refresh_compile_commands(
    name = "refresh_compile_commands",
    targets = [
        "//src/kv:kv_core",
        "//tests:kv_brpc_test_adapter",
        "//bindings/python:_yche_kv",
        "//bindings/python:yche_kv_whl",
        "//tests:kv_store_test",
        "//tests:async_kvcstore_integration_test",
        "//tests:async_kvcstore_thread_pool_test",
        "//tests/async_kvcstore/integration/brpc_e2e_with_store:brpc_rpc_e2e_test",
        "//tests:kv_store_py_test",
        "//smoke:kv_smoke",
        "//smoke:kv_smoke_py",
    ],
)
