load("@rules_cc//cc:defs.bzl", "cc_binary")
load("@rules_python//python:py_binary.bzl", "py_binary")

cc_binary(
    name = "kv_smoke",
    srcs = ["kv_smoke.cc"],
    deps = ["//tests:kv_brpc_test_adapter"],
)

py_binary(
    name = "kv_smoke_py",
    srcs = ["kv_smoke_py.py"],
    main = "kv_smoke_py.py",
    deps = ["//bindings/python:yche_kv"],
)
